const WORKOUT_LIBRARY = [
  {
    id: 'walk-brisk',
    name: 'Brisk Walk',
    category: 'cardio',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'beginner',
    bodyParts: ['legs', 'full body'],
    targetMuscles: ['quadriceps', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipments: ['none'],
    exerciseType: 'CARDIO',
    posture: 'Tall walking posture',
    posture_cues: ['Keep shoulders relaxed.', 'Land softly through the foot.', 'Maintain a steady breathing rhythm.'],
    instructions: ['Start at an easy pace.', 'Drive the arms naturally.', 'Increase pace until you can talk but feel challenged.'],
    exerciseTips: ['Use supportive shoes.', 'Walk briskly, not casually.', 'Stay upright instead of leaning forward.'],
    media: {},
    sets: 1,
    reps: 1,
    duration_min: 20,
    rest_seconds: 45,
    calories_per_min: 6
  },
  {
    id: 'cycling',
    name: 'Cycling / Stationary Bike',
    category: 'cardio',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'beginner',
    bodyParts: ['legs'],
    targetMuscles: ['quadriceps', 'hamstrings'],
    secondaryMuscles: ['glutes'],
    equipments: ['bike'],
    exerciseType: 'CARDIO',
    posture: 'Bike saddle posture',
    posture_cues: ['Keep knees tracking forward.', 'Hinge slightly at the hips.', 'Avoid rounding the lower back.'],
    instructions: ['Sit tall on the saddle.', 'Pedal at a moderate pace.', 'Increase resistance for short intervals if comfortable.'],
    exerciseTips: ['Do not shrug the shoulders.', 'Keep the pedal stroke smooth.', 'Use resistance you can sustain with control.'],
    media: {},
    sets: 1,
    reps: 1,
    duration_min: 18,
    rest_seconds: 45,
    calories_per_min: 7
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climbers',
    category: 'conditioning',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['core', 'full body'],
    targetMuscles: ['abdominals', 'hip flexors'],
    secondaryMuscles: ['shoulders', 'quadriceps'],
    equipments: ['none'],
    exerciseType: 'HIIT',
    posture: 'Strong plank posture',
    posture_cues: ['Stack shoulders over wrists.', 'Keep hips level.', 'Drive knees quickly without bouncing.'],
    instructions: ['Start in a high plank.', 'Alternate knees toward the chest.', 'Move fast while keeping the torso stable.'],
    exerciseTips: ['Press the floor away.', 'Avoid piking the hips.', 'Shorter intervals work best with good speed.'],
    media: {},
    sets: 4,
    reps: 20,
    duration_min: 6,
    rest_seconds: 30,
    calories_per_min: 10
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'strength',
    goalTags: ['weight_loss', 'maintenance', 'muscle_gain'],
    difficulty: 'beginner',
    bodyParts: ['legs'],
    targetMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings'],
    equipments: ['none'],
    exerciseType: 'STRENGTH',
    posture: 'Chest-up squat posture',
    posture_cues: ['Feet just outside hip width.', 'Sit hips back first.', 'Keep knees tracking over toes.'],
    instructions: ['Stand tall.', 'Lower until thighs approach parallel.', 'Drive through the whole foot to stand.'],
    exerciseTips: ['Brace the core before descending.', 'Do not collapse the knees inward.', 'Exhale on the way up.'],
    media: {},
    sets: 4,
    reps: 15,
    duration_min: 8,
    rest_seconds: 40,
    calories_per_min: 7
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    category: 'strength',
    goalTags: ['weight_loss', 'maintenance', 'muscle_gain'],
    difficulty: 'beginner',
    bodyParts: ['legs'],
    targetMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipments: ['none'],
    exerciseType: 'STRENGTH',
    posture: 'Split-stance upright posture',
    posture_cues: ['Keep front foot grounded.', 'Lower straight down.', 'Stay tall through the torso.'],
    instructions: ['Step back with one leg.', 'Lower both knees with control.', 'Push through the front heel to return.'],
    exerciseTips: ['Use a shorter step for more quad focus.', 'Use a longer step for more glute focus.', 'Keep hips square.'],
    media: {},
    sets: 3,
    reps: 12,
    duration_min: 7,
    rest_seconds: 40,
    calories_per_min: 7
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'strength',
    goalTags: ['maintenance', 'muscle_gain', 'weight_loss'],
    difficulty: 'intermediate',
    bodyParts: ['chest', 'upper body'],
    targetMuscles: ['pectorals', 'triceps'],
    secondaryMuscles: ['shoulders', 'core'],
    equipments: ['none'],
    exerciseType: 'STRENGTH',
    posture: 'Rigid plank posture',
    posture_cues: ['Keep a straight line from head to heels.', 'Elbows at about 45 degrees.', 'Hands under shoulders.'],
    instructions: ['Start in a plank.', 'Lower chest toward the floor.', 'Press back up without sagging the hips.'],
    exerciseTips: ['Use knees-down variation if needed.', 'Keep neck neutral.', 'Squeeze glutes and abs.'],
    media: {},
    sets: 4,
    reps: 10,
    duration_min: 6,
    rest_seconds: 45,
    calories_per_min: 8
  },
  {
    id: 'plank',
    name: 'Forearm Plank',
    category: 'core',
    goalTags: ['maintenance', 'weight_loss', 'muscle_gain'],
    difficulty: 'beginner',
    bodyParts: ['core'],
    targetMuscles: ['abdominals'],
    secondaryMuscles: ['glutes', 'shoulders'],
    equipments: ['mat'],
    exerciseType: 'CORE',
    posture: 'Neutral plank alignment',
    posture_cues: ['Elbows under shoulders.', 'Ribs down and core tight.', 'Avoid dropping or piking hips.'],
    instructions: ['Set forearms on the floor.', 'Step both feet back.', 'Hold steady and breathe slowly.'],
    exerciseTips: ['Think long through the spine.', 'Squeeze glutes lightly.', 'Stop before posture breaks.'],
    media: {},
    sets: 3,
    reps: 1,
    duration_min: 4,
    rest_seconds: 30,
    calories_per_min: 5
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'strength',
    goalTags: ['maintenance', 'weight_loss', 'muscle_gain'],
    difficulty: 'beginner',
    bodyParts: ['glutes'],
    targetMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipments: ['mat'],
    exerciseType: 'STRENGTH',
    posture: 'Bridge lockout posture',
    posture_cues: ['Feet flat and hip width.', 'Lift hips without arching the back.', 'Pause at the top.'],
    instructions: ['Lie on your back with knees bent.', 'Drive through the heels.', 'Lower slowly with control.'],
    exerciseTips: ['Keep ribs tucked down.', 'Do not push through the toes.', 'Squeeze glutes hard at the top.'],
    media: {},
    sets: 4,
    reps: 15,
    duration_min: 6,
    rest_seconds: 30,
    calories_per_min: 5
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'strength',
    goalTags: ['muscle_gain', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['back'],
    targetMuscles: ['lats', 'rhomboids'],
    secondaryMuscles: ['biceps', 'rear delts'],
    equipments: ['dumbbell'],
    exerciseType: 'STRENGTH',
    posture: 'Flat-back hinge posture',
    posture_cues: ['Brace the core.', 'Hinge from the hips.', 'Pull elbow toward the hip.'],
    instructions: ['Support yourself on a bench or split stance.', 'Row the weight close to the body.', 'Lower with control.'],
    exerciseTips: ['Avoid twisting the torso.', 'Pause briefly at the top.', 'Keep the neck neutral.'],
    media: {},
    sets: 4,
    reps: 12,
    duration_min: 7,
    rest_seconds: 45,
    calories_per_min: 6
  },
  {
    id: 'shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'strength',
    goalTags: ['muscle_gain', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['shoulders'],
    targetMuscles: ['deltoids'],
    secondaryMuscles: ['triceps', 'upper chest'],
    equipments: ['dumbbell'],
    exerciseType: 'STRENGTH',
    posture: 'Stacked overhead press posture',
    posture_cues: ['Brace abs and glutes.', 'Press straight overhead.', 'Keep wrists stacked over elbows.'],
    instructions: ['Hold weights at shoulder height.', 'Press overhead smoothly.', 'Lower with control.'],
    exerciseTips: ['Avoid arching the lower back.', 'Use a seated version if needed.', 'Keep shoulders down away from ears.'],
    media: {},
    sets: 4,
    reps: 10,
    duration_min: 7,
    rest_seconds: 45,
    calories_per_min: 6
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'strength',
    goalTags: ['muscle_gain', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['posterior chain'],
    targetMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back', 'core'],
    equipments: ['dumbbell'],
    exerciseType: 'STRENGTH',
    posture: 'Hip-hinge posture',
    posture_cues: ['Push hips back.', 'Keep spine neutral.', 'Keep weights close to the legs.'],
    instructions: ['Start standing tall.', 'Hinge until hamstrings stretch.', 'Drive hips forward to stand.'],
    exerciseTips: ['Unlock the knees softly.', 'Move from the hips, not the back.', 'Stop where posture stays neutral.'],
    media: {},
    sets: 4,
    reps: 10,
    duration_min: 7,
    rest_seconds: 50,
    calories_per_min: 6
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['core'],
    targetMuscles: ['obliques'],
    secondaryMuscles: ['abdominals', 'hip flexors'],
    equipments: ['none'],
    exerciseType: 'CORE',
    posture: 'Tall seated twist posture',
    posture_cues: ['Lift the chest.', 'Rotate through the ribs.', 'Keep movement controlled.'],
    instructions: ['Sit with knees bent.', 'Lean back slightly.', 'Rotate side to side while bracing the core.'],
    exerciseTips: ['Do not swing the arms only.', 'Keep the abs engaged.', 'Slow down if the lower back takes over.'],
    media: {},
    sets: 4,
    reps: 20,
    duration_min: 5,
    rest_seconds: 30,
    calories_per_min: 7
  },
  {
    id: 'sit-up',
    name: 'Sit-Up',
    category: 'core',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'beginner',
    bodyParts: ['core'],
    targetMuscles: ['abdominals'],
    secondaryMuscles: ['hip flexors'],
    equipments: ['mat'],
    exerciseType: 'CORE',
    posture: 'Controlled abdominal curl posture',
    posture_cues: ['Keep chin slightly tucked.', 'Lift using the abs.', 'Lower slowly.'],
    instructions: ['Lie on your back with knees bent.', 'Curl up until shoulders clear the floor.', 'Return with control.'],
    exerciseTips: ['Avoid pulling on the neck.', 'Exhale as you rise.', 'Reduce range if the lower back feels strained.'],
    media: {},
    sets: 4,
    reps: 15,
    duration_min: 5,
    rest_seconds: 30,
    calories_per_min: 6
  },
  {
    id: 'heel-touch',
    name: 'Heel Touch',
    category: 'core',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'beginner',
    bodyParts: ['core'],
    targetMuscles: ['obliques'],
    secondaryMuscles: ['abdominals'],
    equipments: ['mat'],
    exerciseType: 'CORE',
    posture: 'Crunch-and-reach posture',
    posture_cues: ['Lift shoulder blades slightly.', 'Reach side to side.', 'Keep abs engaged throughout.'],
    instructions: ['Lie down with knees bent.', 'Lift upper back slightly.', 'Reach toward each heel alternately.'],
    exerciseTips: ['Small range is fine if you feel the obliques.', 'Do not yank the neck forward.', 'Move rhythmically.'],
    media: {},
    sets: 4,
    reps: 24,
    duration_min: 4,
    rest_seconds: 20,
    calories_per_min: 6
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'conditioning',
    goalTags: ['weight_loss', 'maintenance'],
    difficulty: 'intermediate',
    bodyParts: ['full body'],
    targetMuscles: ['calves', 'shoulders'],
    secondaryMuscles: ['core', 'quadriceps'],
    equipments: ['rope'],
    exerciseType: 'HIIT',
    posture: 'Soft landing rope posture',
    posture_cues: ['Stay tall and light on the feet.', 'Rotate through the wrists.', 'Land softly.'],
    instructions: ['Start with light hops.', 'Keep elbows close to the body.', 'Build rhythm before speed.'],
    exerciseTips: ['Use small jumps.', 'Relax the shoulders.', 'Stop if form gets sloppy.'],
    media: {},
    sets: 5,
    reps: 1,
    duration_min: 8,
    rest_seconds: 35,
    calories_per_min: 11
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    category: 'strength',
    goalTags: ['weight_loss', 'maintenance', 'muscle_gain'],
    difficulty: 'beginner',
    bodyParts: ['legs'],
    targetMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipments: ['bench'],
    exerciseType: 'STRENGTH',
    posture: 'Controlled step posture',
    posture_cues: ['Plant the whole foot on the step.', 'Drive through the front leg.', 'Stand tall at the top.'],
    instructions: ['Place one foot on a stable platform.', 'Step up under control.', 'Step down softly and repeat.'],
    exerciseTips: ['Avoid pushing off the back foot too much.', 'Keep knee tracking forward.', 'Use a lower step for beginners.'],
    media: {},
    sets: 3,
    reps: 12,
    duration_min: 6,
    rest_seconds: 35,
    calories_per_min: 7
  }
];
