services:
  - type: web
    name: fitlife-frontend
    runtime: static
    rootDir: .
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
